### ISSUE TITLE
Also add a standalone runner gradle task

### ISSUE THREAD

**Issue by jexp** [sarmbruster/neo4j-csv-firehose#1]
That uses ratpack or undertow to serve the data.

**Comment by sarmbruster** [comment]
Great idea. How about using https://github.com/deephacks/vertxrs ? This way we don't have to change the JAX-RS classes.

**Comment by jexp** [comment]
Yup

And vertxrs could be just a gradle dep not project one to avoid conflicts

Von meinem iPhone gesendet

**Comment by sarmbruster** [comment]
Decided to use undertow. Fixed in https://github.com/sarmbruster/neo4j-csv-firehose/commit/13db3ac1e03f4c9eba81b8dae9b4c1259b249cf6
